config/routes.rb
Rails.application.routes.draw do
  resources :students, only: [:new, :create]
  resources :courses, only: [:new, :create] do
    member { put :add_student }
  end
  root to: 'home#index'
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base
  belongs_to :student
  belongs_to :course
  before_create :set_entry_at

  validates_presence_of :student, :course

  private

  def set_entry_at
    self.entry_at = Time.zone.now
  end
end

app/models/course.rb
class Course < ActiveRecord::Base
  extend EnumerateIt
  has_many :classrooms
  has_many :students, through: :classrooms

  validates_presence_of :name, :description, :status

  has_enumeration_for :status, with: ActivityStatus,
                      create_helpers: { prefix: true }

  def add_student(student_id)
    classrooms.find_or_create_by(student_id: student_id)
  end
end

app/models/student.rb
class Student < ActiveRecord::Base
  extend EnumerateIt
  has_many :classrooms
  has_many :courses, through: :classrooms

  validates_presence_of :name, :register_number, :status
  validates_uniqueness_of :register_number

  has_enumeration_for :status, with: ActivityStatus,
                      create_helpers: { prefix: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  respond_to :html

  def new
    @course = Course.new
    respond_with @course
  end

  def create
    @course = Course.create(course_params)
    respond_with @course, location: root_path
  end

  def add_student
    @course = Course.find(params[:id])
    @course.add_student(params[:classroom][:student_id])
    respond_with @course, location: root_path
  end

  private

  def course_params
    params.require(:course).permit(:name, :description, :status,
                                   classrooms_attributes: [:id, :student_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  respond_to :html

  def index
    @students = Student.all
    @courses = Course.all.includes(:classrooms)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  respond_to :html

  def new
    @student = Student.new
    respond_with @student
  end

  def create
    @student = Student.create(student_params)
    respond_with @student, location: root_path
  end

  private

  def student_params
    params.require(:student).permit(:name, :register_number, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/new.html.slim
= simple_form_for @course do |f|
  = f.input :name
  = f.input :description
  = f.input :status, collection: ActivityStatus.to_a, include_blank: false

  = f.submit

app/views/home/_course_card.html.slim
div(class="card activity-#{course.status}")
  h2.card__title
    = course.name
    span.card__title-status
      = course.status_humanize
  p.card__info-description
    = course.description

  .card__add-student
    = simple_form_for :classroom, url: add_student_course_path(course), method: :put do |f|
      = f.input :student_id, collection: students, label: false, include_blank: false
      = f.submit t('home.course_card.add_student')

  .card__students
    - if course.classrooms.any?
      table
        thead
          tr
            th= Student.human_attribute_name(:name)
            th= Student.human_attribute_name(:register_number)
            th= Student.human_attribute_name(:status)
            th= Classroom.human_attribute_name(:entry_at)
        tbody
          - course.classrooms.each do |classroom|
            tr
              td= classroom.student.name
              td= classroom.student.register_number
              td= classroom.student.status_humanize
              td= l(classroom.entry_at, format: :short)

app/views/home/index.html.slim
- @courses.each do |course|
  = render 'course_card', course: course, students: @students

app/views/layouts/application.html.slim
<!DOCTYPE html>
html
  head
    title IsChallenge
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    header
      h1.header__title
        = link_to root_path, class: 'header__title-link' do
          = fa_icon 'graduation-cap', class: 'header__title-icon'
          = t('application.title')
      .header__links
        = link_to root_path do
          = fa_icon 'home'
          = t('application.header.home')
        = link_to new_student_path
          = fa_icon 'child'
          = t('application.header.create_student')
        = link_to new_course_path
          = fa_icon 'file'
          = t('application.header.create_course')

    .container
      = yield

app/views/students/new.html.slim
= simple_form_for @student do |f|
  = f.input :name
  = f.input :register_number
  = f.input :status, collection: ActivityStatus.to_a, include_blank: false

  = f.submit